EsenioDefaultBundle_Default:
    resource:   "@EsenioDefaultBundle/Controller/DefaultController.php"
    type:       annotation
EsenioDefaultBundle_Event:
    resource:   "@EsenioDefaultBundle/Controller/EventController.php"
    type:       rest
    prefix: /secured

