parameters:
    esenio_default.event_repository.class: Esenio\DefaultBundle\Entity\Event

services:
    esenio_default.event_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %esenio_default.event_repository.class%

