<?php

namespace Esenio\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function getEventsQueryBuilder()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb
            ->select('e')
            ->from('EsenioDefaultBundle:Event', 'e')
        ;
        return $qb;
    }
}
